server:
  port: 8080

spring:
  datasource:
    username: root
    password: Vovik22062008
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    charset: utf8mb4
  jpa:
      hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            ddl-auto: update
            show-sql: true

indexing-settings:
  sites:
  #- url: https://www.svetlovka.ru
 #  name: svetlovka.ru
  - url: https://www.playback.ru
    name: PlayBack.Ru



connection-settings:
  userAgent: Mozilla/5.0 (X11; Fedora;Linux x86; rv:60.0) Gecko/20100101 Firefox/60.0
  referer: https://www.google.com
  timeout: 6000

logging.level.root: INFO